### ISSUE TITLE
Calibration menu needed

### ISSUE THREAD

**Issue by karrots** [markqvist/MicroAPRS#5]
Need a calibration menu similar to other TNCs. Generating tones or combination of tones makes it easier to connect to a system monitor and measure the FM deviation and other parameters while generating constant output audio.

**Comment by IW3IJQ** [comment]
Also gule together Kiss and Aprs firmware, with command to switch mode.

**Comment by tcarwash** [comment]
This would be a big help

**Comment by markqvist** [comment]
I'm probably not going to implement a tone generator / calibration menu. Although I will welcome any pull requests with such features, if it can be fit into the RAM and flash limits of the m328p.

A combined KISS and SimpleSerial firmware is very likely not going to happen, due to RAM and flash constraints of the chip.
